### ISSUE TITLE
Request for release of npm package including micromatch vulnerability fix

### ISSUE THREAD

**Issue by emeitch** [knowledge-work/eslint-plugin-strict-dependencies#106]
It appears that the version of Micromatch with a vulnerability has been fixed in the PR below, but the npm package containing this fix has not yet been released. We kindly request the release of a new npm package that includes this update.

https://github.com/knowledge-work/eslint-plugin-strict-dependencies/pull/103

**Comment by yoshiko-pg** [comment]
@emeitch Thank you for your information. I will publish the current master as soon as possible.

**Comment by yoshiko-pg** [comment]
@emeitch We're published. Thank you for your report.

**Comment by emeitch** [comment]
@yoshiko-pg I have confirmed that the latest version has been released. Thank you for your prompt response!
